// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Personel.Core.UI.Context
{
    public partial class Departman // DTO data transfer object
    {
        public Departman()
        {
            Personel = new HashSet<Personel>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Personel> Personel { get; set; }
    }
}