// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Personel.Core.UI.Context
{
    public partial class Personel
    {
        public int Id { get; set; }
        public int? DepartmanId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public short? Salary { get; set; }
        public int Age => (int)Math.Floor((DateTime.Now - Birthdate.Value).TotalDays / 365);
        public DateTime? Birthdate { get; set; }
        public bool? Gender { get; set; }
        public bool EvliMi { get; set; }

        public virtual Departman Departman { get; set; }  
    }
}